name: lera-fancy-services

networks:
  default:
    driver: bridge
    internal: false
  db_network:
    driver: bridge
    internal: true

volumes:
  languagetool_data:
    name: languagetool_data
  pg_data:
    name: PostgreSQL_data

services:
  syncthing:
    hostname: syncthing
    restart: unless-stopped
    image: syncthing/syncthing:latest
    ports:
      - "8384:8384/tcp"   # Web GUI
      - "22000:22000/tcp" # Sync Protocol
      - "21027:21027/udp" # Local Discovery
    volumes:
      - /var/home/l/Servers/Syncthing:/var/syncthing
      - /var/home/l:/home/l
    environment:
      PUID: 1000
      PGID: 1000
      TZ: America/Recife
    networks:
      - default
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.5'

  languagetool:
    hostname: languagetool
    image: tiol4u/languagetool-server:latest
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      TZ: America/Recife
      PUID: 1000
      PGID: 1000
    deploy:
      resources:
        limits:
          memory: 64M
          cpus: '0.5'
    volumes:
      - languagetool_data:/var/lib/languagetool
    networks:
      - default

  postgresql:
    hostname: PostgreSQL-Server
    restart: unless-stopped
    image: quay.io/fedora/postgresql-18:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - PostgreSQL_data:/var/lib/postgresql/data
    networks:
      - db_network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.5'
